# This workflow will run upon repository creation and clean up
# all files that are not strictly required to build an AEM Live project
# but that we use to develop the project template. This includes this
# particular workflow file.
on:
  create:
    branches:
      - main
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove Helper Files
        run: rm -rf .github/workflows/cleanup-on-create.yaml
        # run: rm -rf some-other-file
        
        # commit back to the repository
      - name: Commit changes
        run: |
          git config --local user.email "helix@adobe.com"
          git config --local user.name "Helix Bot"
          git add .
          git commit -m "chore: cleanup repository template"
          git push